/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.tum.in.ziller.thesis.social_campaign.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.tum.in.ziller.thesis.social_campaign.model.GoogleAccount;
import de.tum.in.ziller.thesis.social_campaign.model.GoogleAccountModel;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the GoogleAccount service. Represents a row in the &quot;zsc_GoogleAccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.tum.in.ziller.thesis.social_campaign.model.GoogleAccountModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GoogleAccountImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a google account model instance should use the {@link de.tum.in.ziller.thesis.social_campaign.model.GoogleAccount} interface instead.
 * </p>
 *
 * @author Markus Ziller
 * @see GoogleAccountImpl
 * @see de.tum.in.ziller.thesis.social_campaign.model.GoogleAccount
 * @see de.tum.in.ziller.thesis.social_campaign.model.GoogleAccountModel
 * @generated
 */
public class GoogleAccountModelImpl extends BaseModelImpl<GoogleAccount>
	implements GoogleAccountModel {
	public static final String TABLE_NAME = "zsc_GoogleAccount";
	public static final Object[][] TABLE_COLUMNS = {
			{ "userProfileId", new Integer(Types.BIGINT) },
			{ "googleAccountId", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table zsc_GoogleAccount (userProfileId LONG not null primary key,googleAccountId VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table zsc_GoogleAccount";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.tum.in.ziller.thesis.social_campaign.model.GoogleAccount"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.tum.in.ziller.thesis.social_campaign.model.GoogleAccount"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.tum.in.ziller.thesis.social_campaign.model.GoogleAccount"));

	public GoogleAccountModelImpl() {
	}

	public long getPrimaryKey() {
		return _userProfileId;
	}

	public void setPrimaryKey(long pk) {
		setUserProfileId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_userProfileId);
	}

	public long getUserProfileId() {
		return _userProfileId;
	}

	public void setUserProfileId(long userProfileId) {
		_userProfileId = userProfileId;
	}

	public String getGoogleAccountId() {
		if (_googleAccountId == null) {
			return StringPool.BLANK;
		}
		else {
			return _googleAccountId;
		}
	}

	public void setGoogleAccountId(String googleAccountId) {
		_googleAccountId = googleAccountId;
	}

	public GoogleAccount toEscapedModel() {
		if (isEscapedModel()) {
			return (GoogleAccount)this;
		}
		else {
			return (GoogleAccount)Proxy.newProxyInstance(GoogleAccount.class.getClassLoader(),
				new Class[] { GoogleAccount.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					GoogleAccount.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		GoogleAccountImpl clone = new GoogleAccountImpl();

		clone.setUserProfileId(getUserProfileId());
		clone.setGoogleAccountId(getGoogleAccountId());

		return clone;
	}

	public int compareTo(GoogleAccount googleAccount) {
		long pk = googleAccount.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		GoogleAccount googleAccount = null;

		try {
			googleAccount = (GoogleAccount)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = googleAccount.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{userProfileId=");
		sb.append(getUserProfileId());
		sb.append(", googleAccountId=");
		sb.append(getGoogleAccountId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("de.tum.in.ziller.thesis.social_campaign.model.GoogleAccount");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>userProfileId</column-name><column-value><![CDATA[");
		sb.append(getUserProfileId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>googleAccountId</column-name><column-value><![CDATA[");
		sb.append(getGoogleAccountId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _userProfileId;
	private String _googleAccountId;
	private transient ExpandoBridge _expandoBridge;
}