/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.tum.in.ziller.thesis.social_campaign.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.tum.in.ziller.thesis.social_campaign.model.GoogleCredentials;
import de.tum.in.ziller.thesis.social_campaign.model.GoogleCredentialsModel;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the GoogleCredentials service. Represents a row in the &quot;zsc_GoogleCredentials&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.tum.in.ziller.thesis.social_campaign.model.GoogleCredentialsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GoogleCredentialsImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a google credentials model instance should use the {@link de.tum.in.ziller.thesis.social_campaign.model.GoogleCredentials} interface instead.
 * </p>
 *
 * @author Markus Ziller
 * @see GoogleCredentialsImpl
 * @see de.tum.in.ziller.thesis.social_campaign.model.GoogleCredentials
 * @see de.tum.in.ziller.thesis.social_campaign.model.GoogleCredentialsModel
 * @generated
 */
public class GoogleCredentialsModelImpl extends BaseModelImpl<GoogleCredentials>
	implements GoogleCredentialsModel {
	public static final String TABLE_NAME = "zsc_GoogleCredentials";
	public static final Object[][] TABLE_COLUMNS = {
			{ "userId", new Integer(Types.BIGINT) },
			{ "googleAccountId", new Integer(Types.VARCHAR) },
			{ "refreshToken", new Integer(Types.VARCHAR) },
			{ "accessToken", new Integer(Types.VARCHAR) },
			{ "expires", new Integer(Types.TIMESTAMP) }
		};
	public static final String TABLE_SQL_CREATE = "create table zsc_GoogleCredentials (userId LONG not null primary key,googleAccountId VARCHAR(500) null,refreshToken VARCHAR(500) null,accessToken VARCHAR(500) null,expires DATE null)";
	public static final String TABLE_SQL_DROP = "drop table zsc_GoogleCredentials";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.tum.in.ziller.thesis.social_campaign.model.GoogleCredentials"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.tum.in.ziller.thesis.social_campaign.model.GoogleCredentials"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.tum.in.ziller.thesis.social_campaign.model.GoogleCredentials"));

	public GoogleCredentialsModelImpl() {
	}

	public long getPrimaryKey() {
		return _userId;
	}

	public void setPrimaryKey(long pk) {
		setUserId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_userId);
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public String getGoogleAccountId() {
		if (_googleAccountId == null) {
			return StringPool.BLANK;
		}
		else {
			return _googleAccountId;
		}
	}

	public void setGoogleAccountId(String googleAccountId) {
		_googleAccountId = googleAccountId;
	}

	public String getRefreshToken() {
		if (_refreshToken == null) {
			return StringPool.BLANK;
		}
		else {
			return _refreshToken;
		}
	}

	public void setRefreshToken(String refreshToken) {
		_refreshToken = refreshToken;
	}

	public String getAccessToken() {
		if (_accessToken == null) {
			return StringPool.BLANK;
		}
		else {
			return _accessToken;
		}
	}

	public void setAccessToken(String accessToken) {
		_accessToken = accessToken;
	}

	public Date getTokenExpirationDate() {
		return _tokenExpirationDate;
	}

	public void setTokenExpirationDate(Date tokenExpirationDate) {
		_tokenExpirationDate = tokenExpirationDate;
	}

	public GoogleCredentials toEscapedModel() {
		if (isEscapedModel()) {
			return (GoogleCredentials)this;
		}
		else {
			return (GoogleCredentials)Proxy.newProxyInstance(GoogleCredentials.class.getClassLoader(),
				new Class[] { GoogleCredentials.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					GoogleCredentials.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		GoogleCredentialsImpl clone = new GoogleCredentialsImpl();

		clone.setUserId(getUserId());
		clone.setGoogleAccountId(getGoogleAccountId());
		clone.setRefreshToken(getRefreshToken());
		clone.setAccessToken(getAccessToken());
		clone.setTokenExpirationDate(getTokenExpirationDate());

		return clone;
	}

	public int compareTo(GoogleCredentials googleCredentials) {
		long pk = googleCredentials.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		GoogleCredentials googleCredentials = null;

		try {
			googleCredentials = (GoogleCredentials)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = googleCredentials.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{userId=");
		sb.append(getUserId());
		sb.append(", googleAccountId=");
		sb.append(getGoogleAccountId());
		sb.append(", refreshToken=");
		sb.append(getRefreshToken());
		sb.append(", accessToken=");
		sb.append(getAccessToken());
		sb.append(", tokenExpirationDate=");
		sb.append(getTokenExpirationDate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append(
			"de.tum.in.ziller.thesis.social_campaign.model.GoogleCredentials");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>googleAccountId</column-name><column-value><![CDATA[");
		sb.append(getGoogleAccountId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>refreshToken</column-name><column-value><![CDATA[");
		sb.append(getRefreshToken());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accessToken</column-name><column-value><![CDATA[");
		sb.append(getAccessToken());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tokenExpirationDate</column-name><column-value><![CDATA[");
		sb.append(getTokenExpirationDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _userId;
	private String _userUuid;
	private String _googleAccountId;
	private String _refreshToken;
	private String _accessToken;
	private Date _tokenExpirationDate;
	private transient ExpandoBridge _expandoBridge;
}