/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.tum.in.ziller.thesis.social_campaign.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.tum.in.ziller.thesis.social_campaign.model.NewsType;
import de.tum.in.ziller.thesis.social_campaign.model.NewsTypeModel;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the NewsType service. Represents a row in the &quot;zsc_NewsType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.tum.in.ziller.thesis.social_campaign.model.NewsTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NewsTypeImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a news type model instance should use the {@link de.tum.in.ziller.thesis.social_campaign.model.NewsType} interface instead.
 * </p>
 *
 * @author Markus Ziller
 * @see NewsTypeImpl
 * @see de.tum.in.ziller.thesis.social_campaign.model.NewsType
 * @see de.tum.in.ziller.thesis.social_campaign.model.NewsTypeModel
 * @generated
 */
public class NewsTypeModelImpl extends BaseModelImpl<NewsType>
	implements NewsTypeModel {
	public static final String TABLE_NAME = "zsc_NewsType";
	public static final Object[][] TABLE_COLUMNS = {
			{ "newsTypeId", new Integer(Types.BIGINT) },
			{ "newsType", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table zsc_NewsType (newsTypeId LONG not null primary key,newsType VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table zsc_NewsType";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.tum.in.ziller.thesis.social_campaign.model.NewsType"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.tum.in.ziller.thesis.social_campaign.model.NewsType"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.tum.in.ziller.thesis.social_campaign.model.NewsType"));

	public NewsTypeModelImpl() {
	}

	public long getPrimaryKey() {
		return _newsTypeId;
	}

	public void setPrimaryKey(long pk) {
		setNewsTypeId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_newsTypeId);
	}

	public long getNewsTypeId() {
		return _newsTypeId;
	}

	public void setNewsTypeId(long newsTypeId) {
		_newsTypeId = newsTypeId;
	}

	public String getNewsType() {
		if (_newsType == null) {
			return StringPool.BLANK;
		}
		else {
			return _newsType;
		}
	}

	public void setNewsType(String newsType) {
		_newsType = newsType;
	}

	public NewsType toEscapedModel() {
		if (isEscapedModel()) {
			return (NewsType)this;
		}
		else {
			return (NewsType)Proxy.newProxyInstance(NewsType.class.getClassLoader(),
				new Class[] { NewsType.class }, new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					NewsType.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		NewsTypeImpl clone = new NewsTypeImpl();

		clone.setNewsTypeId(getNewsTypeId());
		clone.setNewsType(getNewsType());

		return clone;
	}

	public int compareTo(NewsType newsType) {
		long pk = newsType.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		NewsType newsType = null;

		try {
			newsType = (NewsType)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = newsType.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{newsTypeId=");
		sb.append(getNewsTypeId());
		sb.append(", newsType=");
		sb.append(getNewsType());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("de.tum.in.ziller.thesis.social_campaign.model.NewsType");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>newsTypeId</column-name><column-value><![CDATA[");
		sb.append(getNewsTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>newsType</column-name><column-value><![CDATA[");
		sb.append(getNewsType());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _newsTypeId;
	private String _newsType;
	private transient ExpandoBridge _expandoBridge;
}